# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flexible_tunnel_profile.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import jnx_addr_pb2 as jnx__addr__pb2
import prpd_common_pb2 as prpd__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='flexible_tunnel_profile.proto',
  package='routing',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1d\x66lexible_tunnel_profile.proto\x12\x07routing\x1a\x0ejnx_addr.proto\x1a\x11prpd_common.proto\"\xb3\x03\n\x15VxlanTunnelAttributes\x12\x0b\n\x03vni\x18\x01 \x01(\r\x12.\n\rsource_prefix\x18\x02 \x01(\x0b\x32\x17.routing.NetworkAddress\x12\x19\n\x11source_prefix_len\x18\x03 \x01(\r\x12\x34\n\x15source_udp_port_range\x18\x04 \x01(\x0b\x32\x15.jnxBase.NumericRange\x12\'\n\nsource_mac\x18\x05 \x01(\x0b\x32\x13.jnxBase.MacAddress\x12\x34\n\x13\x64\x65stination_address\x18\x06 \x01(\x0b\x32\x17.routing.NetworkAddress\x12\x1c\n\x14\x64\x65stination_udp_port\x18\x07 \x01(\r\x12,\n\x0f\x64\x65stination_mac\x18\x08 \x01(\x0b\x32\x13.jnxBase.MacAddress\x12\r\n\x05\x66lags\x18\t \x01(\r\x12\x39\n\x10rfc7348_reserved\x18\n \x01(\x0b\x32\x1d.routing.Rfc7348VxlanReservedH\x00\x42\x17\n\x15vxlan_header_reserved\"O\n\x14Rfc7348VxlanReserved\x12\x1a\n\x12reserved_bits_8_31\x18\x01 \x01(\r\x12\x1b\n\x13reserved_bits_55_63\x18\x02 \x01(\r\"]\n\x10TunnelAttributes\x12/\n\x05vxlan\x18\x01 \x01(\x0b\x32\x1e.routing.VxlanTunnelAttributesH\x00\x42\x18\n\x16tunnel_attributes_type\"\x97\x01\n\x15\x46lexibleTunnelProfile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x19.routing.TunnelActionType\x12\x16\n\x0einterface_name\x18\x03 \x01(\t\x12-\n\nattributes\x18\x04 \x01(\x0b\x32\x19.routing.TunnelAttributes*4\n\x10TunnelActionType\x12\x0f\n\x0b\x45NCAPSULATE\x10\x00\x12\x0f\n\x0b\x44\x45\x43\x41PSULATE\x10\x01\x62\x06proto3'
  ,
  dependencies=[jnx__addr__pb2.DESCRIPTOR,prpd__common__pb2.DESCRIPTOR,])

_TUNNELACTIONTYPE = _descriptor.EnumDescriptor(
  name='TunnelActionType',
  full_name='routing.TunnelActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENCAPSULATE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECAPSULATE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=845,
  serialized_end=897,
)
_sym_db.RegisterEnumDescriptor(_TUNNELACTIONTYPE)

TunnelActionType = enum_type_wrapper.EnumTypeWrapper(_TUNNELACTIONTYPE)
ENCAPSULATE = 0
DECAPSULATE = 1



_VXLANTUNNELATTRIBUTES = _descriptor.Descriptor(
  name='VxlanTunnelAttributes',
  full_name='routing.VxlanTunnelAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vni', full_name='routing.VxlanTunnelAttributes.vni', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_prefix', full_name='routing.VxlanTunnelAttributes.source_prefix', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_prefix_len', full_name='routing.VxlanTunnelAttributes.source_prefix_len', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_udp_port_range', full_name='routing.VxlanTunnelAttributes.source_udp_port_range', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_mac', full_name='routing.VxlanTunnelAttributes.source_mac', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_address', full_name='routing.VxlanTunnelAttributes.destination_address', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_udp_port', full_name='routing.VxlanTunnelAttributes.destination_udp_port', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_mac', full_name='routing.VxlanTunnelAttributes.destination_mac', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flags', full_name='routing.VxlanTunnelAttributes.flags', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rfc7348_reserved', full_name='routing.VxlanTunnelAttributes.rfc7348_reserved', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='vxlan_header_reserved', full_name='routing.VxlanTunnelAttributes.vxlan_header_reserved',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=78,
  serialized_end=513,
)


_RFC7348VXLANRESERVED = _descriptor.Descriptor(
  name='Rfc7348VxlanReserved',
  full_name='routing.Rfc7348VxlanReserved',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reserved_bits_8_31', full_name='routing.Rfc7348VxlanReserved.reserved_bits_8_31', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reserved_bits_55_63', full_name='routing.Rfc7348VxlanReserved.reserved_bits_55_63', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=594,
)


_TUNNELATTRIBUTES = _descriptor.Descriptor(
  name='TunnelAttributes',
  full_name='routing.TunnelAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vxlan', full_name='routing.TunnelAttributes.vxlan', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='tunnel_attributes_type', full_name='routing.TunnelAttributes.tunnel_attributes_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=596,
  serialized_end=689,
)


_FLEXIBLETUNNELPROFILE = _descriptor.Descriptor(
  name='FlexibleTunnelProfile',
  full_name='routing.FlexibleTunnelProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='routing.FlexibleTunnelProfile.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='routing.FlexibleTunnelProfile.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interface_name', full_name='routing.FlexibleTunnelProfile.interface_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='routing.FlexibleTunnelProfile.attributes', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=692,
  serialized_end=843,
)

_VXLANTUNNELATTRIBUTES.fields_by_name['source_prefix'].message_type = prpd__common__pb2._NETWORKADDRESS
_VXLANTUNNELATTRIBUTES.fields_by_name['source_udp_port_range'].message_type = jnx__addr__pb2._NUMERICRANGE
_VXLANTUNNELATTRIBUTES.fields_by_name['source_mac'].message_type = jnx__addr__pb2._MACADDRESS
_VXLANTUNNELATTRIBUTES.fields_by_name['destination_address'].message_type = prpd__common__pb2._NETWORKADDRESS
_VXLANTUNNELATTRIBUTES.fields_by_name['destination_mac'].message_type = jnx__addr__pb2._MACADDRESS
_VXLANTUNNELATTRIBUTES.fields_by_name['rfc7348_reserved'].message_type = _RFC7348VXLANRESERVED
_VXLANTUNNELATTRIBUTES.oneofs_by_name['vxlan_header_reserved'].fields.append(
  _VXLANTUNNELATTRIBUTES.fields_by_name['rfc7348_reserved'])
_VXLANTUNNELATTRIBUTES.fields_by_name['rfc7348_reserved'].containing_oneof = _VXLANTUNNELATTRIBUTES.oneofs_by_name['vxlan_header_reserved']
_TUNNELATTRIBUTES.fields_by_name['vxlan'].message_type = _VXLANTUNNELATTRIBUTES
_TUNNELATTRIBUTES.oneofs_by_name['tunnel_attributes_type'].fields.append(
  _TUNNELATTRIBUTES.fields_by_name['vxlan'])
_TUNNELATTRIBUTES.fields_by_name['vxlan'].containing_oneof = _TUNNELATTRIBUTES.oneofs_by_name['tunnel_attributes_type']
_FLEXIBLETUNNELPROFILE.fields_by_name['action'].enum_type = _TUNNELACTIONTYPE
_FLEXIBLETUNNELPROFILE.fields_by_name['attributes'].message_type = _TUNNELATTRIBUTES
DESCRIPTOR.message_types_by_name['VxlanTunnelAttributes'] = _VXLANTUNNELATTRIBUTES
DESCRIPTOR.message_types_by_name['Rfc7348VxlanReserved'] = _RFC7348VXLANRESERVED
DESCRIPTOR.message_types_by_name['TunnelAttributes'] = _TUNNELATTRIBUTES
DESCRIPTOR.message_types_by_name['FlexibleTunnelProfile'] = _FLEXIBLETUNNELPROFILE
DESCRIPTOR.enum_types_by_name['TunnelActionType'] = _TUNNELACTIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VxlanTunnelAttributes = _reflection.GeneratedProtocolMessageType('VxlanTunnelAttributes', (_message.Message,), {
  'DESCRIPTOR' : _VXLANTUNNELATTRIBUTES,
  '__module__' : 'flexible_tunnel_profile_pb2'
  # @@protoc_insertion_point(class_scope:routing.VxlanTunnelAttributes)
  })
_sym_db.RegisterMessage(VxlanTunnelAttributes)

Rfc7348VxlanReserved = _reflection.GeneratedProtocolMessageType('Rfc7348VxlanReserved', (_message.Message,), {
  'DESCRIPTOR' : _RFC7348VXLANRESERVED,
  '__module__' : 'flexible_tunnel_profile_pb2'
  # @@protoc_insertion_point(class_scope:routing.Rfc7348VxlanReserved)
  })
_sym_db.RegisterMessage(Rfc7348VxlanReserved)

TunnelAttributes = _reflection.GeneratedProtocolMessageType('TunnelAttributes', (_message.Message,), {
  'DESCRIPTOR' : _TUNNELATTRIBUTES,
  '__module__' : 'flexible_tunnel_profile_pb2'
  # @@protoc_insertion_point(class_scope:routing.TunnelAttributes)
  })
_sym_db.RegisterMessage(TunnelAttributes)

FlexibleTunnelProfile = _reflection.GeneratedProtocolMessageType('FlexibleTunnelProfile', (_message.Message,), {
  'DESCRIPTOR' : _FLEXIBLETUNNELPROFILE,
  '__module__' : 'flexible_tunnel_profile_pb2'
  # @@protoc_insertion_point(class_scope:routing.FlexibleTunnelProfile)
  })
_sym_db.RegisterMessage(FlexibleTunnelProfile)


# @@protoc_insertion_point(module_scope)
