# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='registration_service.proto',
  package='registration',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1aregistration_service.proto\x12\x0cregistration\"\xbf\x01\n\x0fRegisterRequest\x12\x14\n\njson_input\x18\x01 \x01(\tH\x00\x12\x14\n\nfile_input\x18\x02 \x01(\tH\x00\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x13\n\x0bregister_id\x18\x04 \x01(\t\x12\x1b\n\x13skip_authentication\x18\x05 \x01(\x08\x12\x16\n\x0elogical_system\x18\x06 \x01(\t\x12\x18\n\x10routing_instance\x18\x07 \x01(\tB\x0c\n\ninput_type\".\n\rRegisterReply\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2[\n\x08Register\x12O\n\x0fRegisterService\x12\x1d.registration.RegisterRequest\x1a\x1b.registration.RegisterReply\"\x00\x62\x06proto3'
)




_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='registration.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json_input', full_name='registration.RegisterRequest.json_input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_input', full_name='registration.RegisterRequest.file_input', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='registration.RegisterRequest.target', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='register_id', full_name='registration.RegisterRequest.register_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skip_authentication', full_name='registration.RegisterRequest.skip_authentication', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logical_system', full_name='registration.RegisterRequest.logical_system', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='routing_instance', full_name='registration.RegisterRequest.routing_instance', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='input_type', full_name='registration.RegisterRequest.input_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=45,
  serialized_end=236,
)


_REGISTERREPLY = _descriptor.Descriptor(
  name='RegisterReply',
  full_name='registration.RegisterReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='registration.RegisterReply.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='registration.RegisterReply.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=284,
)

_REGISTERREQUEST.oneofs_by_name['input_type'].fields.append(
  _REGISTERREQUEST.fields_by_name['json_input'])
_REGISTERREQUEST.fields_by_name['json_input'].containing_oneof = _REGISTERREQUEST.oneofs_by_name['input_type']
_REGISTERREQUEST.oneofs_by_name['input_type'].fields.append(
  _REGISTERREQUEST.fields_by_name['file_input'])
_REGISTERREQUEST.fields_by_name['file_input'].containing_oneof = _REGISTERREQUEST.oneofs_by_name['input_type']
DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['RegisterReply'] = _REGISTERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'registration_service_pb2'
  # @@protoc_insertion_point(class_scope:registration.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterReply = _reflection.GeneratedProtocolMessageType('RegisterReply', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREPLY,
  '__module__' : 'registration_service_pb2'
  # @@protoc_insertion_point(class_scope:registration.RegisterReply)
  })
_sym_db.RegisterMessage(RegisterReply)



_REGISTER = _descriptor.ServiceDescriptor(
  name='Register',
  full_name='registration.Register',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=286,
  serialized_end=377,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterService',
    full_name='registration.Register.RegisterService',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_REGISTERREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGISTER)

DESCRIPTOR.services_by_name['Register'] = _REGISTER

# @@protoc_insertion_point(module_scope)
